export const EXERCISE_LIST = [
  {
    name: "Goblet Squat",
    movement: "Squat",
    muscleGroup: "Lower Body",
    equipment: "dumbbell",
    skillLevel: "beginner",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "3-1-1",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["core"],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Front Squat",
    movement: "Squat",
    muscleGroup: "Lower Body",
    equipment: "barbell",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "2-1-1",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["core"],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Back Squat",
    movement: "Squat",
    muscleGroup: "Lower Body",
    equipment: "barbell",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "2-1-1",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["core"],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Split Squat",
    movement: "Squat",
    muscleGroup: "Lower Body",
    equipment: "bodyweight/dumbbell",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: true,
    tempo: "2-1-1",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["core"],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Pallof Press",
    movement: "Core",
    muscleGroup: "Core",
    equipment: "cable/band",
    skillLevel: "beginner",
    type: "isolation",
    planeOfMotion: "transverse",
    unilateral: false,
    tempo: "2-0-2",
    primaryMuscles: ["obliques"],
    secondaryMuscles: [],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Plank",
    movement: "Core",
    muscleGroup: "Core",
    equipment: "bodyweight",
    skillLevel: "intermediate",
    type: "isolation",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "isometric",
    primaryMuscles: ["rectus abdominis", "transverse abdominis"],
    secondaryMuscles: [],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Push-Up",
    movement: "Push/Pull",
    muscleGroup: "Upper Body Push",
    equipment: "bodyweight",
    skillLevel: "beginner",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "3-1-1",
    primaryMuscles: ["pectorals", "triceps"],
    secondaryMuscles: ["anterior deltoid", "core"],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Barbell Bench Press",
    movement: "Push/Pull",
    muscleGroup: "Upper Body",
    equipment: "barbell",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "transverse",
    unilateral: false,
    tempo: "2-0-1",
    primaryMuscles: ["pectorals"],
    secondaryMuscles: ["triceps", "anterior deltoid"],
    warmup: false,
    stabilityChallenge: false
  },
  {
    name: "Dumbbell Incline Press",
    movement: "Push/Pull",
    muscleGroup: "Upper Body",
    equipment: "dumbbell",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "2-0-1",
    primaryMuscles: ["upper pectorals"],
    secondaryMuscles: ["triceps", "anterior deltoid"],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Deadbug",
    movement: "Core",
    muscleGroup: "Core",
    equipment: "bodyweight",
    skillLevel: "beginner",
    type: "isolation",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "controlled",
    primaryMuscles: ["transverse abdominis"],
    secondaryMuscles: [],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Trap Bar Deadlift",
    movement: "Hinge",
    muscleGroup: "Posterior Chain",
    equipment: "trap bar",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "2-1-1",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["quads", "lower back"],
    warmup: false,
    stabilityChallenge: false
  },
  {
    name: "Romanian Deadlift",
    movement: "Hinge",
    muscleGroup: "Posterior Chain",
    equipment: "barbell/dumbbell",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "3-1-1",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["lower back"],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Step-Up",
    movement: "Squat",
    muscleGroup: "Lower Body",
    equipment: "dumbbell",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: true,
    tempo: "2-1-1",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Bird Dog",
    movement: "Core",
    muscleGroup: "Core",
    equipment: "bodyweight",
    skillLevel: "beginner",
    type: "isolation",
    planeOfMotion: "sagittal",
    unilateral: true,
    tempo: "hold",
    primaryMuscles: ["erector spinae", "glutes"],
    secondaryMuscles: ["core"],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Pull-Up",
    movement: "Push/Pull",
    muscleGroup: "Upper Body",
    equipment: "bodyweight/assisted",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "frontal",
    unilateral: false,
    tempo: "2-1-1",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "scapular stabilizers"],
    warmup: false,
    stabilityChallenge: false
  },
  {
    name: "Singe Arm DB Row",
    movement: "Push/Pull",
    muscleGroup: "Upper Body",
    equipment: "dumbbell",
    skillLevel: "beginner",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: true,
    tempo: "2-0-1",
    primaryMuscles: ["lats", "rhomboids"],
    secondaryMuscles: ["biceps"],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Inverted Row",
    movement: "Push/pull",
    muscleGroup: "Upper Body",
    equipment: "bar/bodyweight",
    skillLevel: "beginner",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "2-0-1",
    primaryMuscles: ["lats", "traps"],
    secondaryMuscles: ["biceps"],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Farmer Carry",
    movement: "Push/Pull",
    muscleGroup: "Grip/Shoulders",
    equipment: "dumbbell/kettlebell",
    skillLevel: "beginner",
    type: "isolation",
    planeOfMotion: "sagittal",
    unilateral: true,
    tempo: "static",
    primaryMuscles: ["grip", "traps"],
    secondaryMuscles: ["core"],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Banded Face Pulls",
    movement: "Push/Pull",
    muscleGroup: "Upper Body",
    equipment: "band/cable",
    skillLevel: "beginner",
    type: "isolation",
    planeOfMotion: "transverse",
    unilateral: false,
    tempo: "2-0-2",
    primaryMuscles: ["rear delts", "traps"],
    secondaryMuscles: [],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Seated DB Shoulder Press",
    movement: "Push/Pull",
    muscleGroup: "Shoulders",
    equipment: "dumbbell",
    skillLevel: "beginner",
    type: "compound",
    planeOfMotion: "frontal",
    unilateral: false,
    tempo: "2-0-1",
    primaryMuscles: ["deltoids"],
    secondaryMuscles: ["triceps"],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Leg Press",
    movement: "Squat",
    muscleGroup: "Quads",
    equipment: "machine",
    skillLevel: "beginner",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "2-1-1",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes"],
    warmup: false,
    stabilityChallenge: false
  },
  {
    name: "Walking Lunges",
    movement: "Squat",
    muscleGroup: "Quads/Glutes",
    equipment: "bodyweight or dumbbell",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: true,
    tempo: "2-1-1",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Split Squat",
    movement: "Squat",
    muscleGroup: "Quads/Glutes",
    equipment: "bodyweight or dumbbell",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: true,
    tempo: "2-1-1",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["core"],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Hanging Leg Raise",
    movement: "Core",
    muscleGroup: "Core",
    equipment: "bodyweight",
    skillLevel: "intermediate",
    type: "isolation",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "controlled",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: ["hip flexors"],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Side Plank",
    movement: "Core",
    muscleGroup: "Core/Obliques",
    equipment: "bodyweight",
    skillLevel: "intermediate",
    type: "isolation",
    planeOfMotion: "transverse",
    unilateral: true,
    tempo: "controlled",
    primaryMuscles: ["obliques"],
    secondaryMuscles: ["transverse abdominis"],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Barbell Row",
    movement: "Push/Pull",
    muscleGroup: "Back",
    equipment: "barbell",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "horizontal",
    unilateral: false,
    tempo: "2-0-2",
    primaryMuscles: ["lats", "rhomboids"],
    secondaryMuscles: ["biceps", "rear delts"],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Lat Pulldown",
    movement: "Push/Pull",
    muscleGroup: "Lats",
    equipment: "cable",
    skillLevel: "beginner",
    type: "compound",
    planeOfMotion: "frontal",
    unilateral: false,
    tempo: "2-1-2",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps"],
    warmup: false,
    stabilityChallenge: false
  },
  {
    name: "Rear Delt Fly",
    movement: "Push/Pull",
    muscleGroup: "Rear Delts",
    equipment: "machine or cable",
    skillLevel: "beginner",
    type: "isolation",
    planeOfMotion: "transverse",
    unilateral: false,
    tempo: "2-1-2",
    primaryMuscles: ["rear deltoids"],
    secondaryMuscles: ["traps"],
    warmup: false,
    stabilityChallenge: false
  },
  {
    name: "Hip Thrust",
    movement: "Hinge",
    muscleGroup: "Glutes",
    equipment: "barbell or machine",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "2-1-1",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Seated Hamstring Curl",
    movement: "Squat",
    muscleGroup: "Hamstrings",
    equipment: "machine",
    skillLevel: "beginner",
    type: "isolation",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "2-1-2",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    warmup: false,
    stabilityChallenge: false
  },
  {
    name: "Calf Raise",
    movement: "Squat",
    muscleGroup: "Calves",
    equipment: "machine or bodyweight",
    skillLevel: "beginner",
    type: "isolation",
    planeOfMotion: "vertical",
    unilateral: false,
    tempo: "2-1-2",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    warmup: false,
    stabilityChallenge: false
  },
  {
    name: "Woodchopper",
    movement: "Core",
    muscleGroup: "Obliques",
    equipment: "cable or dumbell",
    skillLevel: "intermediate",
    type: "isolation",
    planeOfMotion: "transverse",
    unilateral: true,
    tempo: "controlled",
    primaryMuscles: ["obliques"],
    secondaryMuscles: ["core"],
    warmup: false,
    stabilityChallenge: true
  },
  {
    name: "Worlds Greatest Stretch",
    movement: "Full Body",
    muscleGroup: "Full Body",
    equipment: "bodyweight",
    skillLevel: "all",
    type: "mobility",
    planeOfMotion: "multi",
    unilateral: true,
    tempo: "controlled",
    primaryMuscles: ["hip flexors", "thoracic spine"],
    secondaryMuscles: ["hamstrings", "quads"],
    warmup: true,
    stabilityChallenge: true
  },
  {
    name: "Deep Squat Hold",
    movement: "Squat",
    muscleGroup: "Lower Body",
    equipment: "bodyweight",
    skillLevel: "all",
    type: "mobility",
    planeOfMotion: "sagittal/transverse",
    unilateral: false,
    tempo: "isometric",
    primaryMuscles: ["hips", "thoracic spine"],
    secondaryMuscles: [],
    warmup: true,
    stabilityChallenge: true
  },
  {
    name: "Ankle Rockers",
    movement: "Squat",
    muscleGroup: "Lower Body",
    equipment: "bodyweight",
    skillLevel: "all",
    type: "mobility",
    planeOfMotion: "sagittal",
    unilateral: true,
    tempo: "controlled",
    primaryMuscles: ["ankles"],
    secondaryMuscles: [],
    warmup: true,
    stabilityChallenge: false
  },
  {
    name: "Cat-Cow",
    movement: "Full Body",
    muscleGroup: "Spine",
    equipment: "bodyweight",
    skillLevel: "all",
    type: "mobility",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "controlled",
    primaryMuscles: ["spine"],
    secondaryMuscles: [],
    warmup: true,
    stabilityChallenge: false
  },
  {
    name: "Glute Bridge",
    movement: "Squat",
    muscleGroup: "Posterior Chain",
    equipment: "bodyweight",
    skillLevel: "beginner",
    type: "activation",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "2-1-1",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    warmup: true,
    stabilityChallenge: true
  },
  {
    name: "Bodyweight Squats",
    movement: "Squat",
    muscleGroup: "Lower Body",
    equipment: "bodyweight",
    skillLevel: "beginner",
    type: "activation",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "3-1-1",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: [],
    warmup: true,
    stabilityChallenge: false
  },
  {
    name: "Banded Lateral Walks",
    movement: "Squat",
    muscleGroup: "Glutes",
    equipment: "band",
    skillLevel: "all",
    type: "activation",
    planeOfMotion: "frontal",
    unilateral: false,
    tempo: "controlled",
    primaryMuscles: ["glute medius"],
    secondaryMuscles: [],
    warmup: true,
    stabilityChallenge: true
  },
  {
    name: "Band Pull-Aparts",
    movement: "Push/Pull",
    muscleGroup: "Shoulders",
    equipment: "band",
    skillLevel: "all",
    type: "activation",
    planeOfMotion: "transverse",
    unilateral: false,
    tempo: "2-1-2",
    primaryMuscles: ["rear deltoids", "traps"],
    secondaryMuscles: [],
    warmup: true,
    stabilityChallenge: false
  },
  {
    name: "Scapular Push-Ups",
    movement: "Push/Pull",
    muscleGroup: "Scapular Stabilizers",
    equipment: "bodyweight",
    skillLevel: "all",
    type: "activation",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "controlled",
    primaryMuscles: ["serratus anterior"],
    secondaryMuscles: [],
    warmup: true,
    stabilityChallenge: true
  },
  {
    name: "Banded Good Mornings",
    movement: "Hinge",
    muscleGroup: "Posterior Chain",
    equipment: "band",
    skillLevel: "beginner",
    type: "activation",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "controlled",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: [],
    warmup: true,
    stabilityChallenge: false
  },
  {
    name: "Shoulder Dislocates",
    movement: "Push/Pull",
    muscleGroup: "Shoulders",
    equipment: "band",
    skillLevel: "beginner",
    type: "mobility",
    planeOfMotion: "transverse",
    unilateral: false,
    tempo: "controlled",
    primaryMuscles: ["deltoids"],
    secondaryMuscles: [],
    warmup: true,
    stabilityChallenge: false
  },
  {
    name: "Dead Hang",
    movement: "Push/Pull",
    muscleGroup: "Shoulders/Grip",
    equipment: "bar",
    skillLevel: "all",
    type: "mobility",
    planeOfMotion: "vertical",
    unilateral: false,
    tempo: "static",
    primaryMuscles: ["lats", "grip"],
    secondaryMuscles: [],
    warmup: true,
    stabilityChallenge: true
  },
  {
    name: "Scapular Pull-Ups",
    movement: "Push/Pull",
    muscleGroup: "Scapular Stabilizers",
    equipment: "bar",
    skillLevel: "intermediate",
    type: "activation",
    planeOfMotion: "vertical",
    unilateral: false,
    tempo: "controlled",
    primaryMuscles: ["traps", "rhomboids"],
    secondaryMuscles: [],
    warmup: true,
    stabilityChallenge: true
  }
];
