export const EXERCISE_LIST = [
  {
    name: "Goblet Squat",
    movement: "Squat",
    muscleGroup: "Lower Body",
    equipment: "dumbbell",
    skillLevel: "beginner",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "3-1-1",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["core"],
    stabilityChallenge: true
  },
  {
    name: "Front Squat",
    movement: "Squat",
    muscleGroup: "Lower Body",
    equipment: "barbell",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "2-1-1",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["core"],
    stabilityChallenge: true
  },
  {
    name: "Back Squat",
    movement: "Squat",
    muscleGroup: "Lower Body",
    equipment: "barbell",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "2-1-1",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["core"],
    stabilityChallenge: true
  },
  {
    name: "Split Squat",
    movement: "Squat",
    muscleGroup: "Lower Body",
    equipment: "bodyweight/dumbbell",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: true,
    tempo: "2-1-1",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["core"],
    stabilityChallenge: true
  },
  {
    name: "Pallof Press",
    movement: "Squat",
    muscleGroup: "Core",
    equipment: "cable/band",
    skillLevel: "beginner",
    type: "isolation",
    planeOfMotion: "transverse",
    unilateral: false,
    tempo: "2-0-2",
    primaryMuscles: ["obliques"],
    secondaryMuscles: [],
    stabilityChallenge: true
  },
  {
    name: "RKC Plank",
    movement: "Squat",
    muscleGroup: "Core",
    equipment: "bodyweight",
    skillLevel: "intermediate",
    type: "isolation",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "isometric",
    primaryMuscles: ["rectus abdominis", "transverse abdominis"],
    secondaryMuscles: [],
    stabilityChallenge: true
  },
  {
    name: "Push-Up",
    movement: "Bench Press",
    muscleGroup: "Upper Body Push",
    equipment: "bodyweight",
    skillLevel: "beginner",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "3-1-1",
    primaryMuscles: ["pectorals", "triceps"],
    secondaryMuscles: ["anterior deltoid", "core"],
    stabilityChallenge: true
  },
  {
    name: "Barbell Bench Press",
    movement: "Bench Press",
    muscleGroup: "Upper Body Push",
    equipment: "barbell",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "transverse",
    unilateral: false,
    tempo: "2-0-1",
    primaryMuscles: ["pectorals"],
    secondaryMuscles: ["triceps", "anterior deltoid"],
    stabilityChallenge: false
  },
  {
    name: "Dumbbell Incline Press",
    movement: "Bench Press",
    muscleGroup: "Upper Body Push",
    equipment: "dumbbell",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "2-0-1",
    primaryMuscles: ["upper pectorals"],
    secondaryMuscles: ["triceps", "anterior deltoid"],
    stabilityChallenge: true
  },
  {
    name: "SA Cable Chest Press",
    movement: "Bench Press",
    muscleGroup: "Upper Body Push",
    equipment: "cable",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "transverse",
    unilateral: true,
    tempo: "2-0-2",
    primaryMuscles: ["pectorals"],
    secondaryMuscles: ["triceps", "core"],
    stabilityChallenge: true
  },
  {
    name: "Deadbug w/ Reach",
    movement: "Bench Press",
    muscleGroup: "Core",
    equipment: "bodyweight",
    skillLevel: "beginner",
    type: "isolation",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "controlled",
    primaryMuscles: ["transverse abdominis"],
    secondaryMuscles: [],
    stabilityChallenge: true
  },
  {
    name: "Trap Bar Deadlift",
    movement: "Deadlift",
    muscleGroup: "Posterior Chain",
    equipment: "trap bar",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "2-1-1",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["quads", "lower back"],
    stabilityChallenge: false
  },
  {
    name: "Romanian Deadlift",
    movement: "Deadlift",
    muscleGroup: "Posterior Chain",
    equipment: "barbell/dumbbell",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "3-1-1",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["lower back"],
    stabilityChallenge: true
  },
  {
    name: "Step-Up",
    movement: "Deadlift",
    muscleGroup: "Lower Body",
    equipment: "dumbbell",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: true,
    tempo: "2-1-1",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    stabilityChallenge: true
  },
  {
    name: "Cable Pull-Through",
    movement: "Deadlift",
    muscleGroup: "Posterior Chain",
    equipment: "cable",
    skillLevel: "beginner",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "2-1-2",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    stabilityChallenge: true
  },
  {
    name: "Bird Dog",
    movement: "Deadlift",
    muscleGroup: "Core",
    equipment: "bodyweight",
    skillLevel: "beginner",
    type: "isolation",
    planeOfMotion: "sagittal",
    unilateral: true,
    tempo: "hold",
    primaryMuscles: ["erector spinae", "glutes"],
    secondaryMuscles: ["core"],
    stabilityChallenge: true
  },
  {
    name: "Pull-Up",
    movement: "Pull-Up",
    muscleGroup: "Upper Body Pull",
    equipment: "bodyweight/assisted",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "frontal",
    unilateral: false,
    tempo: "2-1-1",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "scapular stabilizers"],
    stabilityChallenge: false
  },
  {
    name: "1-Arm DB Row",
    movement: "Pull-Up",
    muscleGroup: "Upper Body Pull",
    equipment: "dumbbell",
    skillLevel: "beginner",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: true,
    tempo: "2-0-1",
    primaryMuscles: ["lats", "rhomboids"],
    secondaryMuscles: ["biceps"],
    stabilityChallenge: true
  },
  {
    name: "Inverted Row",
    movement: "Pull-Up",
    muscleGroup: "Upper Body Pull",
    equipment: "bar/bodyweight",
    skillLevel: "beginner",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "2-0-1",
    primaryMuscles: ["lats", "traps"],
    secondaryMuscles: ["biceps"],
    stabilityChallenge: true
  },
  {
    name: "Farmer Carry",
    movement: "Pull-Up",
    muscleGroup: "Grip/Shoulders",
    equipment: "dumbbell/kettlebell",
    skillLevel: "beginner",
    type: "isolation",
    planeOfMotion: "sagittal",
    unilateral: true,
    tempo: "static",
    primaryMuscles: ["grip", "traps"],
    secondaryMuscles: ["core"],
    stabilityChallenge: true
  },
  {
    name: "Banded Face Pulls",
    movement: "Pull-Up",
    muscleGroup: "Upper Body Pull",
    equipment: "band/cable",
    skillLevel: "beginner",
    type: "isolation",
    planeOfMotion: "transverse",
    unilateral: false,
    tempo: "2-0-2",
    primaryMuscles: ["rear delts", "traps"],
    secondaryMuscles: [],
    stabilityChallenge: true
  },
  {
    name: "Seated DB Shoulder Press",
    movement: "Overhead Press",
    muscleGroup: "Shoulders",
    equipment: "dumbbell",
    skillLevel: "beginner",
    type: "compound",
    planeOfMotion: "frontal",
    unilateral: false,
    tempo: "2-0-1",
    primaryMuscles: ["deltoids"],
    secondaryMuscles: ["triceps"],
    stabilityChallenge: true
  },
  {
    name: "Incline DB Press",
    movement: "Bench Press",
    muscleGroup: "Upper Chest",
    equipment: "dumbbell",
    skillLevel: "beginner",
    type: "compound",
    planeOfMotion: "transverse",
    unilateral: false,
    tempo: "2-0-1",
    primaryMuscles: ["pectorals (upper)", "anterior deltoids"],
    secondaryMuscles: ["triceps"],
    stabilityChallenge: true
  },
  {
    name: "Cable Lateral Raise",
    movement: "Lateral Raise",
    muscleGroup: "Lateral Deltoids",
    equipment: "cable",
    skillLevel: "beginner",
    type: "isolation",
    planeOfMotion: "frontal",
    unilateral: true,
    tempo: "2-1-2",
    primaryMuscles: ["lateral deltoids"],
    secondaryMuscles: [],
    stabilityChallenge: false
  },
  {
    name: "Rope Triceps Pushdown",
    movement: "Triceps Extension",
    muscleGroup: "Triceps",
    equipment: "cable",
    skillLevel: "beginner",
    type: "isolation",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "2-0-1",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    stabilityChallenge: false
  },
  {
    name: "Leg Press",
    movement: "Squat",
    muscleGroup: "Quads",
    equipment: "machine",
    skillLevel: "beginner",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "2-1-1",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes"],
    stabilityChallenge: false
  },
  {
    name: "Walking Lunges",
    movement: "Lunge",
    muscleGroup: "Quads/Glutes",
    equipment: "bodyweight or dumbbell",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: true,
    tempo: "2-1-1",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    stabilityChallenge: true
  },
  {
    name: "Bulgarian Split Squat",
    movement: "Split Squat",
    muscleGroup: "Quads/Glutes",
    equipment: "bodyweight or dumbbell",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: true,
    tempo: "2-1-1",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["core"],
    stabilityChallenge: true
  },
  {
    name: "Hanging Leg Raise",
    movement: "Leg Raise",
    muscleGroup: "Core",
    equipment: "bodyweight",
    skillLevel: "intermediate",
    type: "isolation",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "controlled",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: ["hip flexors"],
    stabilityChallenge: true
  },
  {
    name: "Side Plank Reach Through",
    movement: "Plank",
    muscleGroup: "Core/Obliques",
    equipment: "bodyweight",
    skillLevel: "intermediate",
    type: "isolation",
    planeOfMotion: "transverse",
    unilateral: true,
    tempo: "controlled",
    primaryMuscles: ["obliques"],
    secondaryMuscles: ["transverse abdominis"],
    stabilityChallenge: true
  },
  {
    name: "Barbell Row",
    movement: "Row",
    muscleGroup: "Back",
    equipment: "barbell",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "horizontal",
    unilateral: false,
    tempo: "2-0-2",
    primaryMuscles: ["lats", "rhomboids"],
    secondaryMuscles: ["biceps", "rear delts"],
    stabilityChallenge: true
  },
  {
    name: "Cable Lat Pulldown",
    movement: "Lat Pulldown",
    muscleGroup: "Lats",
    equipment: "cable",
    skillLevel: "beginner",
    type: "compound",
    planeOfMotion: "frontal",
    unilateral: false,
    tempo: "2-1-2",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps"],
    stabilityChallenge: false
  },
  {
    name: "Incline DB Curl",
    movement: "Curl",
    muscleGroup: "Biceps",
    equipment: "dumbbell",
    skillLevel: "beginner",
    type: "isolation",
    planeOfMotion: "sagittal",
    unilateral: true,
    tempo: "2-1-2",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    stabilityChallenge: false
  },
  {
    name: "Rear Delt Fly",
    movement: "Reverse Fly",
    muscleGroup: "Rear Delts",
    equipment: "machine or cable",
    skillLevel: "beginner",
    type: "isolation",
    planeOfMotion: "transverse",
    unilateral: false,
    tempo: "2-1-2",
    primaryMuscles: ["rear deltoids"],
    secondaryMuscles: ["traps"],
    stabilityChallenge: false
  },
  {
    name: "RDL",
    movement: "Deadlift",
    muscleGroup: "Hamstrings/Glutes",
    equipment: "barbell or dumbbell",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "3-1-1",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["lower back"],
    stabilityChallenge: true
  },
  {
    name: "Hip Thrust",
    movement: "Hip Thrust",
    muscleGroup: "Glutes",
    equipment: "barbell or machine",
    skillLevel: "intermediate",
    type: "compound",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "2-1-1",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    stabilityChallenge: true
  },
  {
    name: "Seated Hamstring Curl",
    movement: "Leg Curl",
    muscleGroup: "Hamstrings",
    equipment: "machine",
    skillLevel: "beginner",
    type: "isolation",
    planeOfMotion: "sagittal",
    unilateral: false,
    tempo: "2-1-2",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    stabilityChallenge: false
  },
  {
    name: "Calf Raise",
    movement: "Calf Raise",
    muscleGroup: "Calves",
    equipment: "machine or bodyweight",
    skillLevel: "beginner",
    type: "isolation",
    planeOfMotion: "vertical",
    unilateral: false,
    tempo: "2-1-2",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    stabilityChallenge: false
  },
  {
    name: "Woodchopper",
    movement: "Rotation",
    muscleGroup: "Obliques",
    equipment: "cable or dumbell",
    skillLevel: "intermediate",
    type: "isolation",
    planeOfMotion: "transverse",
    unilateral: true,
    tempo: "controlled",
    primaryMuscles: ["obliques"],
    secondaryMuscles: ["core"],
    stabilityChallenge: true
  }
];
